import java.io.File;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.Scanner;

public class Main {
    public static void main(String[] args) {
        int[] arr = new int[5]; //start of prob 1
        arr[0] = 1;
        arr[1] = 3;
        arr[2] = 5;
        arr[3] = 15;
        arr[4] = 23;
        ChangeMoney m1 = new ChangeMoney(16072, arr);
        //System.out.println(m1.getMinCoins()); //End prob1

        File txt3 = new File("rosalind_ba5b.txt"); //Start of prob 2
        Scanner in = new Scanner(System.in);
        ArrayList<String> strings = new ArrayList<>();
        try {
            in = new Scanner(txt3);
        } catch (FileNotFoundException e) {
            throw new RuntimeException(e);
        }
        String[] tempNumArr = new String[2];
        int n = 0;
        int m = 0;
        if(in.hasNext()){
            String nums = in.nextLine();
            tempNumArr = nums.split(" ");
            n = Integer.parseInt(tempNumArr[0]);
            m = Integer.parseInt(tempNumArr[1]);
        }
        int[][] arrDown = new int[n + 1][m + 1];
        int[][] arrRight = new int[n + 1][m + 1];
        int sides = 0;
        int rows = 1;
        int check = 0;
        while(in.hasNext()){
            String sample = in.nextLine();
            String[] str = new String[sample.length()];
            if(sample.contains("-")){
                check = 1;
                sample = in.nextLine();
            }
            str = sample.split(" ");
            if(check == 0) {
                for (int i = 0; i < str.length; i++) {
                    arrDown[rows][i] = Integer.parseInt(str[i]);
                }
                rows++;
            }
            else {
                for (int j = 1; j < str.length + 1; j++) {
                    arrRight[sides][j] = Integer.parseInt(str[j - 1]);
                }
                sides++;
            }
        }
        OptimalPath optimalPath1 = new OptimalPath(n, m, arrDown, arrRight);
        //System.out.println(optimalPath1.getLengthOfPath());
        String str1 = "AGAGAGTCTGTGTGCAGAGACCCCGTCCAGTATAATAATCGTTGGGCTGCACTCAATATTGTGCTATATCCCACGGCCGCTAATTTGAATTCATAAAAAACTCAACATCTGATCTTGTATGGATTAACCAGAAGTAGGGAATCGATGCGTCTAGTATAGAACCCTTTCTGCATAGTCGAGTTACCACTTCAGGGGCACCGACGGGGAACACGATCAGGTCTAGGAACTTAGAGTGCCCCCGTCACGTCCGCGCCATGTCACATGCAGCTCTTGATCATCGCACCCACGTTCAGTACAACAAACCGGGAATTCGCGACGTACGCGCAGTCCACATATCCGATCTCGGTCAACTGAGGACTCCCGGGACACGCCTAACAGAGACCGGGTTTCGAGTTCTGTTCGTGACGTCTGGGGGCTACCTGGGAGCTCGCCATAGCATGTAGAGTGAGTAACCTCATGTAGTCGCGGTTACAAAGTCAGTAAATATAAGAGCCATCATATGAGCATGTGTAACCCAACGCGATTGTGCTGCACGGTACTCGCGCGATAGTGCAGTGTACGCAGTTATACGAAGATGCGCCGGGGATGTTCCGGCGCTGGTAAGGTACTGAAATGGTTACAGGGTTCGGAGATGCCGCTCACAATCCGGGATACCACGGTTGATGGACTATGGGCTAAATGGAAAAATATTCGCCGGAGGGGTTCGAGCTGCCGACAGAACACTGTGGACCCCGCAGAAAGGGCGTAGTTCTGTCTGGCAAGAGCACCATGTCCGATTAGATTCATTCGCCATGTTGAATAGCCCAGCCGTTTCCTTTGACTCAATCACA";
        String str2 = "GGAAAGGAGACTATTCGTTCCTAGTACCTTGAGCCTAACCCACAGAATGATGTCGTTCGGACTTGCGGATGTGTCGCCTACAACGGATAGCAAGCGTGTTAGGCTAGAGATAAGTAGGCCGCAAGGGCAACATTCTAAGGGATCTAATCCAAGGTCCAGAATCAACCGATCGAGTTTGAAATTCAAGGACCATGGTCTCGTACGTTCATTAAGGGCATTGAGAGATAGATTCCATTGCTGAGGGCGTCACGATAACTGAGCTATCACCAGTCCCCATTTGCAGCGCGGCGAGGAAGGGATCGTATGCCAAATTCCATATTAACAAACTTAGGCTCACTAGGGAGCCTTCTGGGGGACCTAGGAGTCGAGGCAATTGGCACCAGTCTCAGTATAACGCTCTGCGCCTTATTGCTTCGCCAACGGCACTCTTGTGCCAGGGGACACGGGGAGCGACGTTCAATTAGGATTGCTCCAAACAGGCTGGGTGTTGATCGGATTTTCGGAGGACACGGGGTGTACCTCTAGGGGCTCGCTTAATGCGTGTCTGTTAATCACTCTGTCCGTTAGAATCGATGTCTTTAGGCCTAGGCATGTTACTCACTTACCTGTCCTAAGGGGCGGTTGGATATCCACGGAGGATTCGGAATCACAAACGAGCCGTTCCAACGCGGGATCTATAATTTAAATTATAACTCAACATATCCTCTTTTGAGTTGTGTGGGGAGCGATTCCAATGAAAACATAGCCCGTCCAAACGAGATACTCGGGTTTTTCAAGATCCAGTGATTAAACTAATGTGGCCACGATTTCAATTAAGGGTCGCGACGCCTTGCCGGGCGTTATTCCGGTCGCACATTAAT";
        LongestCommonSeq l1 = new LongestCommonSeq(str1.length(), str2.length(), str1, str2);
        //System.out.println(l1.OutputLCS(l1.getBacktrack(), str1, str1.length(), str2.length()));
        File txt = new File("rosalind_ba5d.txt");

        ///Start of prob 2

        Scanner in2 = new Scanner(System.in);
        int source = 11;
        int sink = 38;
        int count = 0;
        ArrayList<String> str = new ArrayList<>();
        try {
            in2 = new Scanner(txt);
        } catch (FileNotFoundException e) {
            throw new RuntimeException(e);
        }
        while(in2.hasNext()) {
            String sample = in2.nextLine();
            str.add(sample);
        }
        str.removeFirst();
        str.removeFirst();
        ArrayList<int[]> graph = new ArrayList<>();
        /*str.add("0->1:7");
        str.add("0->2:4");
        str.add("2->3:2");
        str.add("1->4:1");
        str.add("3->4:3");*/
        for(String strand: str){
            int[] group = new int[3];
            group[0] = Integer.parseInt(strand.substring(0, strand.indexOf("-")));
            group[1] =  Integer.parseInt(strand.substring(strand.indexOf(">") + 1, strand.indexOf(":")));
            group[2] =  Integer.parseInt(strand.substring(strand.indexOf(":") + 1));
            graph.add(group);
        }
        DAGProb d1 = new DAGProb(graph, source, sink);
        //System.out.println(d1.LongestPath());
        //System.out.println(d1.getPath());

        ///Start of prob 3
        allignment a1 = new allignment("CNWTIYHVGTSYEHIHSRPTTEKYGENKQNKTLFDDAHGRLPLYLEQRVGPTLAGCHRKYEWQYETQKDTNEYHNMYPAPGNFDQGWKRCSRWCAEKINTCFYHNADCHEMHPFCLFMAHVGPTLLINRQNQLPMVYAPTWWKMFLMFHFSNWKAMIMHFEDLPRTPLFGPMPIFYGVGWYLYEPRGGGGAQKSPRCCLQMSFIYQWWMDSGYDAIICLQKYMTMHMRTCHGAYSSQFYGCMQMKKIDYTPTVLHPEPTRSGLALTFFRALFTVAEFMNYTHCISTGPTRNAGVWMIEKNKVERPLNIPQSWYFNCPNTDAVLNVKFSCNCGGCWVPSACNIQYILMWDVTIQKAEGSDYKDPKMMLMMLKDEPWCQSYNCKSGGFNAWDDDLWDNHNKMFAALYTIGTAQSYIFPFQFTFGAPLGGNMRRTRMCHIVCQKEKRAYYKAVHGDTTPAAHNYTRTGNSLNHNYQGPCVGLHWSRQVWIMEWHYGHVTPDSKNSRSGSETFYSVGVTGKVLRGDHFNPDHMQVYWEKCPQNPDSQWWCAREIQLWRRGNLQRYEWPRMTYCGMYSLTAKYKCYVMTGIRQLKRDEYLHILLDSARGTTMRHSKLRLWQRDLWNHSVRCTYHELPRWPLSEVPDFKRPVQTSRAEHYGTYYNWALKPCIAGIVNANKDYTEDSPHCIYFERPNNIIWKCCLLWSQQNPKIDKYQAQMMEEYCHRWNALPCCKSFWCKIDVCGICILCSFEQCHPLWASMPNENFCQDRRAPQECWLNQKNFAQWKRKPEEIMPNFQYDGCRVIGENGHDVIQLYTATYEKCPDKQYKNPHNEGAMCYLHWFKESNKSRVLHMDKCYVQDTNNHTVTWDFNHESQKTIETGCATKWYSETMSWDGDVWDKSYHILSLWDHATHMWFDAGHLLIVMMWFNYFYTRWRCQPFIQGVRVESHPMQFTTWGEIHRCSGAQYPWGERFGDFPQTGNPQGLRSRGYLNPFLMKAALSGPHHGKCETGSNAFIFWKTWHKWWSYPFHVIHFWWDSGKHYNGTPVPQVMFDRHVKGAQHSETNKCLWVFYARYPKSEKAEQISKENSKLKPCHLEHANMSGVTLLSRYNGTVKDMSHSLTGPRTDQRWHIPADEISEKWAEPSYFDTKNQVHKTTTCQYSHENANQLYIFKHYMALSIDVQRGPDDDSGWRLHITRQNIWECSDQHYLLQKDRPRYTTVGDRVDQYAGVNYLELPAKTYYAMTCWPQCAQVSGTMNAKTATLTNWPAGGHIKVWLSMQGMHDDNGMMKRRYPRVSKLDARQRRRYQCIPYQEVHHCREAFELTHRPQSGDLFEAVMMFPVSHNPRTFPMVWFEGYYECDDKLGQIHTNVQMTSLLWEHEDGDHRLGLIANLELTHWVSNMWIQCYMVGSFPELLRCFVFNYEYIFHRMGEYPFCNNFLIMPFDPTMLQRCTGYCEITNDDEPMELWRCALVKDGEGASNYRLLYLDPPEAVTLHNSVSHYNKVIIDWNMGYIWEVGGEFDGQPNNPTTPWSQFKDGFDVQFYFSVDRAWFLYQPGGTVKLFPEPACCKVKELIIQNVDRHIHQNCYKMQTFVEDYEPTYPNRKRHWGRPWQSKNWKDADLGHYLFHRISGAVWAYKVRLEWDKASMVYPLTQVFQTSGKKQIEPIEEFHRINTKTSWQSPVWHTHELIDKQFFPGFMDTMWKHKLIISHNMMSCVHFNLRQMRQFDRARKFEMTWFCFSLPWKNHNECAISQYHVCIPRHLAFWRCAMIYKDYPICSNAEQMHINSFKGPRMHSAMADEYYVELHVSYPSPHRKVKGGNTDSAAESICHQMWTYRFMYTGTMETENTYTFYRTRQMSFHPKTTSEECLSGADREYVYFPHVPEPIADDTQGARFFRLVQFHLQYEQRHYIQHLWLGFDFLGGDSNRWHDSPPDSERVNVGMAQKNDTRLLAEAEIYHFIMWHSLAGVDADWWNHFRGLPVWYERGLSGEWYFLEMCFRRSIQSEMFYTGISLTVRAISQFEKGQQQGMANAIAIMIKFRCMMMPYEIISGYAHRDRDDHPLDCSLDMVSHQSEEHNWIMMTWNVQCVWRRLCHGSHNCEQPWEAINNMFEPEGMNQYKPAMDMIFELGCLNMEYSKWMWYGPRDCHLFRREILNMYDTYVFQIKTVGLVTKTKMRESDISICEAKFFARMHKCMYYFWQVQVTEHITTMVSIFKGNYGTEDQTCWYWMELMDYLTKVLFTIRKKRDPYFDPGKAATCYALHLEKHCMRQDLGFDKKTFPGAPNGTRSWCGHTQHYYHYGSARHTADNNHDTREQGAPWFSGKVKWDFYSEYDDPVLAKKELVMPFQHVCIYHQMMIRGLNYISRWGILQFEIAWTACHCHYIEMNGNNVLVTPRESRKPKDMLPPAFKVVYSFTMNECHQILVPCGTETMTCLWDHLMRFEMLFIVWVFTLMHWYMNPTCVQNLMYSNRYWSDTRFEAYWEIIQMKSGRTLSYFHNKVPRVRWEILGKISNPRNEYCKYHPTRDEHAVRQSQISGVFMNEALEHNTELHRTSWHFFTTSMHLLSKADIWFNMPTTRVHDTRYRWSGTTWQWWQGHVRIPMSLDSMHQEDKEIYPPKAGNGEGLYPIWNGMDLMQDNHHAGSVMCISNNSWQQRIEWFPKKLKGCMGYMNDHPLTVYCEARSGFNRNDQFLGDERWRLEHVGAANDNSCELEKPCIMSVSFWWACSKGLAIAFCNHRVLTQMRFLSNAKASDDWCVPRAGHPADTQYFLSTWFMNHQNSGEIWTFPLGAIYGSHRWWADRCALHIYNLFNVYQQINYRPFPQPTVSLIKEYLFLFPHFTGMTCSAEGYLEQELMEIMEVNQQWVNEWAVTTWAMMMMKWPYAQVHNGFVQFHHYCHPKVPQKNTMWMIHTNWHYYYVITCGPVDFTKQSSAPNHMALPCPGPSGTDSKRACWWEICQWWAMMWIKGWCINVFYNNRAAMAFAGPPWYHENTTLRGIPLWHFFLQNGSIGDVWDICKIQCDMNTDHMESFNKKIKMYRMDNNTFRKKYFCECMYFHEYNCDMTMLNCCNDREMNGIRVGWEHCGLTPTAFQSGQRAQRYIQISSWDFPPGVYTTARWNNTVANIDWWWTFYHEFHFAGNGFFGNAWCKCRLNKESPQCMAGWGSRMNNIKNYIQMNANATNRPFMFAAQINMKKRKNFLQSGEQRFWRVWCHPMQYISWHQSDNTEQGNIQYMCYLAMIFSSQGGPYKACDFLYDQHWRFGAILYHFKIAHRAIPQRTQPLWKRHDSMDWTMGFGQKHGYCAEPYGKRVTTTWDQKFTPCNGTAFYFYLMHTFQRALMESNGNIDTQIFIQECHDMHCTHGCGAGCPFHMFIIVTKTHFRSGRLTGVHLPDLWPKPYEIPQHRASTSVGAQKWTYETSHMEVMTWANLVQIPTMMKKVCGYSMQNKMSMMMFSYFWNTSACPKRQHYAENWQIPVCCWIEKIEIMQTCAMETDDLRMFNWWDYMWRPFFIRNMGGEQPLNRYTQRFRYWKWNVLNMLQYCGVMAFSVQYWMTGRRRMVGMHACDDCFRCEYHVPAEAMAAYAKWLMPAFMDHAIYSHCTKASIAIHCLYRYKQWWEPQWTLCLKGMGAIGRQWKERSGKPLWNFCSPLFLFFLSARHWVKGDQLEVKYWDQWMYRNMASFGGENSEYIDMLGEYPGRDIHNWNNNYMLSRADFDHCVVHRGFRLGIGKMEIRCMFQCDNSLHMPQSGSDWHARDPTDWIHWQRFDIWVKWIIFCRCDIYMVMEYCFDMEPDRRAMGTKIHTLTYYYLWKQIPSGVSLMLHTFPEMQVTHWIIDQVKGMNCLSCCYYSKSMCADARIHLQWYSKRNRNMYIQEYACETTFSTDMEGEANFMAFWASQRRRIICIARPGCVNASANFGCFATVDIPGMSQYTSDPKMHNCMPGAQNIEYNYWINTNYFYELCLCMEGHPIWKPWHLFKEDIVTWPHRMGNNPMLPIHSLAGEGPYTKYTCYWVRPGERCRVVQIPAMIEPMPVSGAGVINCRVCHVWEYKLDETYKENIYYKEEDHTRLLWPLWDPYHWEYPGPSDGFIPGGKLGYLENGNFAEMSIPAKEYVHVEGREYYRWTHWTYVDPFANLLKVCRYHSRISYLPHCIYHDWEVPDCCDWVHGFLIMIKEVTLELPCNQAMLVGQKQDWAVWTNRYPRHPKVRDCRNINNCGSCWCAWDTTFVMYLQSHNPYNIHWHMNWYEHRNGPIV", "CNWTIMSYEHIHTTESWCKRSLSGWNMWMNKTLWAIFRDDAHGRWPLRVGPWLARCHRKYEWQYETQKPENQLCTNHYVNMPAPGNFDQGWKRCNRWEAEKINTCNYHNADCIEDHKFCLAMAHVGPTLLINRQNQFLIMPDPMAKISMRDTYHEEDLDRTPLTGPMPIFYGVGWYLYEPFGGGGVGWKSPRECLQMSFIYQWWQIICLQKYMQVQVRCQHDMHMRTCHGSQFYGCMWMHPEPTRSGLALRALFTVAEFMNYTNNGKASHFCISTGPTWNGLIEETRRNREHLKQDNIPQSWYFGCPFTYRYHFSCNCGGCWVPSACMSDVTIQKAEGSDYKKDMLMMLKDECWCQSYNCKSGGCNDDLTDNHMKMVAALYTIGTAQSYIFLFAPLGGNMRRTRMCHICEKGDQWYQFVWEMFPAQNSLNHNGLHWSRQKEGWDPHRRWIMEWHYKHVTPDSKNSRSGSTFYSVGVTGDVLFGDHFDHVTDLAGFALKVYWEKCPQNPDSQWWRMREIQLTERGGNLQRYEWPRITYCGMDSLTANRKCYVMIIRQLKRDVFCYIEFNYLHILETTMRKQCADFKLRLWQFDPWEHSVPWYDCWLHELGRWPLSEVCDFKRPVQTSRAEHYGSTCEGSQLRHCLMHKVYNWALKANKDRTQDSPHCICDNGFFERPNNIIWKCCLLWSQQNPKIDKYQAQMMEEYCHRWNALPCCKSFGEYCHIDVCGICILRSFEQNPCMKWNWDDYSNENFCQDRRPAKWLNQKNFAQWKRKIEEIMPDFQYDGCRVIGENRHDVIELYTATYLRCRAAKCPFNPHNEGAMCYLHNIRAVNKGRVLHLDKTYVNNHTVTWDTSSCYHESQKTIETKLMKKIGDWCATKWDRMCWNLRFSERMAKWHLEARDWDGDFWDKSYTHQHDHATHMAGHLLMMWFGNFEGQKYFIQGVRVTAMMLKTSWGWDTDPQIARHARSFFYTCMGERFGDPDWNQHELMYQSGNVLSRGYAELSHPWPTPQHNWHKSPTVYPIPTNKGCSYIKLQFHVVPQVMNERDRHVETNKCLWVSYARYPKSEKIYRELSCMEQIAIENSKLKPCHGEHANKNALLGSGVMLKSRYNGTTQDGFGPCTDQMWHIPCDEIVCWYRYYEKTAEPSYFHTEATAPGNQVHKTTTQYYQQYSVHPSQNCYSYDENYMALNIDNQRGPDDWHGCCCEFLGARLHWKDNFSSHYLDQKACCMKLPRYTTVGDRAGVRVVPHMMGQKRLELPAIMTCWPQCAQVNWPAPTGSGHIKTPWWLSDHYEDWRFSGRMKRRYIRVSKLDFRQCRKSQCIPYQEVHHCREAFGDCRPSLTHRPQNGHHMDEVSTNPRTFPMVWFCGYECDAKLGQIHTNVVMTSLLFRSVEHEDGDHRLGLIANRWRPWAMCFVFEYIDKWYQTWHRMGEWPFCNNFLIMPFDPTMLERCTGYCEITNDDEPKELWYPWKQQNCALVKFGEGASNYRLLWCLIYLDPPEAVTLHNSVTVNYEHQIHYFGNIIDNMGYIDRRNHFASKPCYGRLHFQTCPKSTTFKDGFDVQFYFSVDFAWFCWYKECKTVKQPGGTVKLFPEPACCKVHMHGYENEAEIQDETSWFVEDYTNPRPWQSENWKDADLGHYLFKAVWAYIEGQNYSRMSFWTNLRLEWDKASMVEPLTQVFQTSGKFVIEEEFNRITSWQSPLMYWHDETHELIDKQFFPGFWDTMWKHKHWQRWEWSMMSCRQSVLANAHFNLRIMRQFDRARKFEMTAFCFSLWKNHNEGFAISQCEDFVPNLQPRHLAFWPICKNAYLMYFTVGIFHSIRSFKGPRMHSAMADEYYVELHVSYQATHTDSAAESICHQMMTYRFMLGTMETENTYTFYRTKQMSFHPKTTSEECLSGADREYAYFPHVDDGQGMKYHHQYEQRHYIAHLGDSNRWHDSPPDYERVNVGMAHPNEAKQYHDFIMWPSLAGVDADWWNRGLPVWMHIATAMQCWYFLEPCFRKMFYSLTVRAQQGMANAIAIMIKFRCMMMPYEIISGYAGCSLDMVSHQIMMTWNVWISAVIRQLCHWELTNNMFEPEGMNQYMDPMWMTAGPAMDMIGCLNMQYSLWPITATYEDAPFHSIQMHLFMYMGDWVGLVQANGYNPNNQDISICEKKFFAREHKCVQVTIHIWHACQTMVSIFKGNEMDHFGTEDYTCWYWMEQKCYLTKDSKSRDPYFDTCYQMGLHLERTYPDLDPAHCRQDGAPNGTRSFKSCGHDYGMAIDRIDNNHDTREQGAPWFSAKVKWDFFEYDDLVVGTEIPVKTPTCWSQHRQMMIRGLIGGILQIAWTACHCTIICVYIEMNGNNVLSITPLPPAFETADLPVDVYRFTECQQIVMNTCKEWHQWDKMLGGTETWDHLNMRIGDNTFEMLWVFTLMHWYDNPTGVQNLMYSNRYWSDRGLNFAEAYWEIICDFMKSGRTLSYFSNKVAWIQRARVRWEILGKISNKRNEYCKYHQSMIHQVFMKTYLCVLCGEALEHNTELHRTSAEFFTTSMNLLSKQARMVCGHDINFFNMPTHDTYIIYRAPNWNWWQGDVRIPMSEDSMHQIWILEGLYPEWNGMDDMQDNHHAGSVMCISECVAANEWFPCKTKWCMGYMQQSLYREYCEAISGFNAGNVIDQFLRPDEYDERWRLEHVGAANDNSCEAEKPCIMSSPKYIFWWQCSKWLAIAFCNQHRVLTQMRFLSMAKAPLWMVCTGDDWCVPGHPFGTYPWLMLQYESTENLGEIWTFMETTLWLLAIYGSVDWWADRQIGPIKTKGALHPFPMPCVSLIKEYLFLFPHFTGMTCSAEGYLEQLMEYKNFVGSMPNQQWVNEWAVTTWAMMMMKGFVADHADAFHHYDKNTMWMIHTNTHNYYPVSQTKQSSAPNHMLLPCPKMETKGRRKVKCQWWHMMWIKGWCINVFMNNLKCSMMPHGPPWYLETYRPDHGCPLWHFDVWDICKIQCDMNTDHMESNSFKWNKHWEWKSQKIKMYRMDNYFHEYNCDFLCCNDREMNGISNCTPTAFQSGQRAQRYMTGHPEWDFPLPTYCQIGVYTTARWNDGHNRMTVANEFFHIGNAWCKCTWNKESPQCMAGWGSRMYIQMVANADNRPMFHANIKNGSQMKKRKNFLQSGEQRFWWDPQRVWCHPMQYGSTGHGRMIISSIEGMYKRCIERWTGIMNFLYDQGWRFGAIPIHFIIATRAIPQRYQPYTKRHDSMDWTMGLGQKHGYCAEPYGKRVPMKDDMIMVTEWDQKFTPCFYFYLNHTFQRALMRSNGNTQIFIQECHDMHCTHGMPPEIVTKTTFRMGRLTGVHLPDLWPKPYEIPQHRASTSAAISGETSHNEVMTWANLIKFQTKASCGYSMQMMMFSYFWNTSACPKQIPVCCWIEKIEIMQTKAMETDRCTEPRLMFNWIDYMRPFFDWRNGILLGTHQRFRYWNVLNMLQYYQRWYCFIGVMAVHIVEDFIWQYMTGRFVVFDCFCEMLWHVPRECKWLMFEDHAIYNPIYYWKIAIHCLYRYKNNKWDLWEPQWTLCLKDMQWKERSGKDLWNFCSPLVLIFLSARKGDQYEREIKYWDQWMASFGLENSETARGMTPQEIDMLMHYPGRDIIWWWRRENWNNYMLSRAEFDHLVYHMGFHLGIGKMEMYVDAVRCMFQCDNILHWHARDPTDWIWWKLFQVFFHFSHRDDKEKMDRRAMGMLIRRKRKIHSAKGLTSGMGWPKWIRHTFPEMQVTHWIIDQVKGMNCLSCCYYSKSMDVQNQDATIHLQWYSKHLFNKADDCNMYIQEYACETTFETDAWWASQRRRCICIVRPGCVTKKKASANFGKFATVDINGGLGMDQYTSPKMCNCMPGKQNIEYCYWINTNDADRDYEFFYELFSAIGMNDMEGHPFARQICWKPWHLFKEDIVTKVAVYPHRMGDPPSNQELTLSGDETTTYWVWVGERCRVVQIPAMIQPMPVSGAGVISVNADKLNRVCHVTYKENIYYKEEHTRLLWNPIWDNNYHWHYPGPSDGFIPNGNFAPMSIPAKEYVHVEDREYYRWTHWTYVDPFAMVWGMFLVCRYHTKWYWASVRISYLPCILHDWEVPWSACMDFLFNCDWVHGFLTQSRHIKELEGQVWTNRDKVNCGSCWCAWDYDCVMYLWHMNWYEHRIGPIR");
        //allignment a1 = new allignment("TGTTA", "TCGTC");
        System.out.println(a1.getScore());
        System.out.println(a1.getCorrectedSet());

        
    }
}